package cd;

import cn.hutool.core.util.ServiceLoaderUtil;
import dd.j;
import java.lang.ref.SoftReference;
import java.lang.ref.WeakReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.URI;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.DayOfWeek;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Month;
import java.time.MonthDay;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.time.Period;
import java.time.ZonedDateTime;
import java.time.temporal.TemporalAccessor;
import java.util.Calendar;
import java.util.Currency;
import java.util.Date;
import java.util.Locale;
import java.util.Optional;
import java.util.TimeZone;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicLongArray;
import java.util.concurrent.atomic.AtomicReference;
import java.util.concurrent.atomic.DoubleAdder;
import java.util.concurrent.atomic.LongAdder;
import kd.g;
import kd.h;
import rd.l;

/* JADX INFO: compiled from: r8-map-id-47d7031f5d78718531f48f1c7640d5b20aa4ef3796b143da36b974009fbbf949 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class e {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final f f3984a;

    static {
        f fVar = new f();
        l lVar = new l();
        fVar.f3985i = lVar;
        Class cls = Integer.TYPE;
        lVar.put(cls, new dd.d(cls));
        l lVar2 = fVar.f3985i;
        Class cls2 = Long.TYPE;
        lVar2.put(cls2, new dd.d(cls2));
        l lVar3 = fVar.f3985i;
        Class cls3 = Byte.TYPE;
        lVar3.put(cls3, new dd.d(cls3));
        l lVar4 = fVar.f3985i;
        Class cls4 = Short.TYPE;
        lVar4.put(cls4, new dd.d(cls4));
        l lVar5 = fVar.f3985i;
        Class cls5 = Float.TYPE;
        lVar5.put(cls5, new dd.d(cls5));
        l lVar6 = fVar.f3985i;
        Class cls6 = Double.TYPE;
        lVar6.put(cls6, new dd.d(cls6));
        l lVar7 = fVar.f3985i;
        Class cls7 = Character.TYPE;
        lVar7.put(cls7, new dd.d(cls7));
        l lVar8 = fVar.f3985i;
        Class cls8 = Boolean.TYPE;
        lVar8.put(cls8, new dd.d(cls8));
        fVar.f3985i.put(Number.class, new dd.d());
        fVar.f3985i.put(Integer.class, new dd.d(Integer.class, 1));
        fVar.f3985i.put(AtomicInteger.class, new dd.d(AtomicInteger.class, 1));
        fVar.f3985i.put(Long.class, new dd.d(Long.class, 1));
        fVar.f3985i.put(LongAdder.class, new dd.d(LongAdder.class, 1));
        fVar.f3985i.put(AtomicLong.class, new dd.d(AtomicLong.class, 1));
        fVar.f3985i.put(Byte.class, new dd.d(Byte.class, 1));
        fVar.f3985i.put(Short.class, new dd.d(Short.class, 1));
        fVar.f3985i.put(Float.class, new dd.d(Float.class, 1));
        fVar.f3985i.put(Double.class, new dd.d(Double.class, 1));
        fVar.f3985i.put(DoubleAdder.class, new dd.d(DoubleAdder.class, 1));
        fVar.f3985i.put(Character.class, new dd.b(6));
        fVar.f3985i.put(Boolean.class, new dd.b(4));
        fVar.f3985i.put(AtomicBoolean.class, new dd.b(0));
        fVar.f3985i.put(BigDecimal.class, new dd.d(BigDecimal.class, 1));
        fVar.f3985i.put(BigInteger.class, new dd.d(BigInteger.class, 1));
        fVar.f3985i.put(CharSequence.class, new j());
        fVar.f3985i.put(String.class, new j());
        fVar.f3985i.put(URI.class, new dd.b(19));
        fVar.f3985i.put(URL.class, new dd.b(20));
        fVar.f3985i.put(Calendar.class, new dd.b(5));
        fVar.f3985i.put(Date.class, new dd.d(Date.class, 0));
        fVar.f3985i.put(ed.c.class, new dd.d(ed.c.class, 0));
        fVar.f3985i.put(java.sql.Date.class, new dd.d(java.sql.Date.class, 0));
        fVar.f3985i.put(Time.class, new dd.d(Time.class, 0));
        fVar.f3985i.put(Timestamp.class, new dd.d(Timestamp.class, 0));
        fVar.f3985i.put(TemporalAccessor.class, new dd.d(Instant.class, 4));
        fVar.f3985i.put(Instant.class, new dd.d(Instant.class, 4));
        fVar.f3985i.put(LocalDateTime.class, new dd.d(LocalDateTime.class, 4));
        fVar.f3985i.put(LocalDate.class, new dd.d(LocalDate.class, 4));
        fVar.f3985i.put(LocalTime.class, new dd.d(LocalTime.class, 4));
        fVar.f3985i.put(ZonedDateTime.class, new dd.d(ZonedDateTime.class, 4));
        fVar.f3985i.put(OffsetDateTime.class, new dd.d(OffsetDateTime.class, 4));
        fVar.f3985i.put(OffsetTime.class, new dd.d(OffsetTime.class, 4));
        fVar.f3985i.put(DayOfWeek.class, new dd.d(DayOfWeek.class, 4));
        fVar.f3985i.put(Month.class, new dd.d(Month.class, 4));
        fVar.f3985i.put(MonthDay.class, new dd.d(MonthDay.class, 4));
        fVar.f3985i.put(Period.class, new dd.b(16));
        fVar.f3985i.put(Duration.class, new dd.b(10));
        fVar.f3985i.put(WeakReference.class, new dd.d(WeakReference.class, 3));
        fVar.f3985i.put(SoftReference.class, new dd.d(SoftReference.class, 3));
        fVar.f3985i.put(AtomicReference.class, new dd.b(3));
        fVar.f3985i.put(AtomicIntegerArray.class, new dd.b(1));
        fVar.f3985i.put(AtomicLongArray.class, new dd.b(2));
        fVar.f3985i.put(TimeZone.class, new dd.b(18));
        fVar.f3985i.put(Locale.class, new dd.b(11));
        fVar.f3985i.put(Charset.class, new dd.b(7));
        fVar.f3985i.put(Path.class, new dd.b(15));
        fVar.f3985i.put(Currency.class, new dd.b(9));
        fVar.f3985i.put(UUID.class, new dd.b(21));
        fVar.f3985i.put(StackTraceElement.class, new dd.b(17));
        fVar.f3985i.put(Optional.class, new dd.b(13));
        fVar.f3985i.put(g.class, new dd.b(12));
        fVar.f3985i.put(h.class, new dd.b(14));
        ServiceLoaderUtil.load(c.class).forEach(new d(fVar, 0));
        f3984a = fVar;
    }
}
