package pc;

/* JADX INFO: compiled from: r8-map-id-47d7031f5d78718531f48f1c7640d5b20aa4ef3796b143da36b974009fbbf949 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class i {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final g f23373a;

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final b f23374b;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    public static final b f23375c;

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    public static final b f23376d;

    static {
        new b("VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK", 0);
        new b("OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER", 0);
        new b("SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE", 4);
        new b("DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS", 1);
        new b("START_SAFE_BROWSING", "START_SAFE_BROWSING", 5);
        new b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST", 5);
        new b("SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST", 5);
        new b("SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST", 5);
        new b("SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL", 5);
        new b("SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE", 1);
        new b("SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE", 1);
        new b("SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS", 1);
        new b("SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS", 1);
        new b("SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS", 1);
        new b("SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", 1);
        new b("RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR", 0);
        new b("RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR", 0);
        new b("SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS", 1);
        new b("SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT", 5);
        new b("WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT", 1);
        new b("WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION", 0);
        new b("WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE", 0);
        new b("SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", 5);
        new b("SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED", 5);
        new b("SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", 5);
        new b("WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE", 0);
        new b("WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE", 0);
        new b("WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER", 2);
        new b("WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", 0);
        new b("CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL", 0);
        new b("POST_WEB_MESSAGE", "POST_WEB_MESSAGE", 0);
        new b("WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE", 0);
        new b("GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT", 4);
        new b("GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT", 4);
        new b("GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER", 7);
        new b("WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE", 7);
        new b("TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE", 6);
        new e();
        new e();
        new e();
        new b("WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", 7);
        f23373a = new g();
        new b("PROXY_OVERRIDE", "PROXY_OVERRIDE:3", 2);
        f23374b = new b("MULTI_PROCESS", "MULTI_PROCESS_QUERY", 2);
        f23375c = new b("FORCE_DARK", "FORCE_DARK", 7);
        f23376d = new b("FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR", 2);
        new b("WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER", 2);
        new b("DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1", 2);
        new b("PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS", 2);
        new b("GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER", 2);
        new b("ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", 2);
        new b("GET_COOKIE_INFO", "GET_COOKIE_INFO", 2);
        new b("REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST", 2);
        new b("USER_AGENT_METADATA", "USER_AGENT_METADATA", 2);
        new h("USER_AGENT_METADATA_FORM_FACTORS", "USER_AGENT_METADATA", 0);
        new h("MULTI_PROFILE", "MULTI_PROFILE", 1);
        new b("ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR", 2);
        new b("WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS", 2);
        new b("MUTE_AUDIO", "MUTE_AUDIO", 2);
        new b("WEB_AUTHENTICATION", "WEB_AUTHENTICATION", 2);
        new b("SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING", 2);
        new b("BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE", 2);
        new b("BACK_FORWARD_CACHE_SETTINGS", "BACK_FORWARD_CACHE_SETTINGS", 2);
        new b("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V3", "BACK_FORWARD_CACHE_SETTINGS_V3", 2);
        new b("BACK_FORWARD_CACHE_SETTINGS_EXPERIMENTAL_V4", "BACK_FORWARD_CACHE_SETTINGS_V4", 2);
        new b("DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA", 2);
        new h("PREFETCH_URL_V5", "PREFETCH_URL_V5", 2);
        new b("ASYNC_WEBVIEW_STARTUP_V2");
        new b("ASYNC_WEBVIEW_STARTUP");
        new b("ASYNC_WEBVIEW_STARTUP_ASYNC_STARTUP_LOCATIONS");
        new b("DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING", 2);
        new b("PRERENDER_URL_V2", "PRERENDER_URL_V3", 2);
        new b("SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2", 2);
        new b("PREFETCH_CACHE_V1", "PREFETCH_CACHE_V1", 2);
        new b("SET_MAX_PRERENDERS_V1", "SET_MAX_PRERENDERS_V1", 2);
        new b("SAVE_STATE", "SAVE_STATE", 2);
        new b("NAVIGATION_GET_WEB_RESOURCE_ERROR", "NAVIGATION_GET_WEB_RESOURCE_ERROR", 2);
        new b("NAVIGATION_LISTENER", "PAGE_GET_URL", 2);
        new b("PROVIDER_WEAKLY_REF_WEBVIEW", "PROVIDER_WEAKLY_REF_WEBVIEW", 2);
        new b("PAYMENT_REQUEST", "PAYMENT_REQUEST", 2);
        new b("WEBVIEW_BUILDER_EXPERIMENTAL_V1", "WEBVIEW_BUILDER_V1", 2);
        new b("WEBVIEW_BUILDER_EXPERIMENTAL_V2", "WEBVIEW_BUILDER_V2", 2);
        new b("COOKIE_INTERCEPT", "COOKIE_INTERCEPT", 2);
        new b("WARM_UP_RENDERER_PROCESS", "WARM_UP_RENDERER_PROCESS", 2);
        new b("ORIGIN_MATCHED_HEADERS", "EXTRA_HEADER_FOR_ORIGINS", 2);
        new b("CUSTOM_REQUEST_HEADERS", "CUSTOM_REQUEST_HEADERS", 2);
        new e();
        new e();
        new e();
        new b("PRECONNECT", "PRECONNECT", 2);
        new b("ADD_QUIC_HINTS", "ADD_QUIC_HINTS_V1", 2);
        new b("HYPERLINK_CONTEXT_MENU_ITEMS", "HYPERLINK_CONTEXT_MENU_ITEMS", 2);
        new b("JS_INJECTION_IN_FRAME_AND_WORLD", "JS_INJECTION_IN_FRAME_AND_WORLD", 2);
    }
}
